heaven-frontend:
  ports:
  - 80:80/tcp
  - 443:443/tcp
  environment:
    CONTAINER_DNS_TEMPLATE: $$name.$$name
    DNS_RESOLVER: 169.254.169.250
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  tty: true
  image: extremeprog/heaven
  stdin_open: true

