.catalog:
  version: 1
  questions:
    - variable: CONTAINER_DNS_TEMPLATE
      description: "Specify how heaven's nginx will find your services. Possible variables are $name and $version for patterns: $name.domain.com, $version.$name.domain.com, $name.subdomain.domain.com, $version.$name.subdomain.domain.com."
      label: "Container's DNS template"
      required: true
      type: string
      default: $name.$name
heaven-frontend:
  scale: 1
balancer:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000