name: "Proxy Container for Git"
description: "Proxy container for use private github, bitbucket, ... without password. You can use private docker builds and add private rancher templates."
version: "1.1"
category: Utils
version: 1