name: "Proxy Container for Git"
description: "Proxy container for applying private github, bitbucket, ... without password. You can use private docker builds and add private rancher templates."
version: 1.0-rancher1
category: Utils