msa-primary:
  labels:
    io.rancher.sidekicks: msa-datavolume
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  tty: true
  image: extremeprog/mongo-sites-api
  volumes_from:
  - msa-datavolume
  stdin_open: true
msa-datavolume:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  tty: true
  command: /bin/true
  image: extremeprog/mongo-sites-api
  volumes:
  - /var/lib/mongo-sites-api/mongodb:/var/lib/mongodb
  stdin_open: true