mongo-sites-api:
  labels:
    io.rancher.sidekicks: msa-datavolume
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: 'true'
  tty: true
  image: extremeprog/mongo-sites-api
  volumes_from:
  - msa-datavolume
  stdin_open: true
msa-datavolume:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  tty: true
  command: /bin/true
  net: none
  image: extremeprog/mongo-sites-api
  volumes:
  - /var/lib/mongodb
  stdin_open: true
heaven-backend:
  image: rancher/dns-service
  links:
  - mongo-sites-api:mongo-sites-api