mongo-sites-api:
  labels:
    io.rancher.sidekicks: msa-datavolume
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label_soft: heaven=1
    io.rancher.container.hostname_override: container_name
  tty: true
  image: extremeprog/mongo-sites-api
  volumes_from:
  - msa-datavolume
  stdin_open: true
msa-datavolume:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
    io.rancher.container.hostname_override: container_name
  tty: true
  command:
  - /bin/true
  image: extremeprog/mongo-sites-api
  volumes:
  - /var/lib/mongodb
  stdin_open: true
  net: none
heaven-backend:
  image: rancher/dns-service
  links:
  - mongo-sites-api