git-proxy:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  tty: true
  environment:
      PRIVATE_KEY: ${PRIVATE_KEY}
  image: extremeprog/git-proxy
  stdin_open: true