name: "Heaven (based on Nginx)"
description: "HTTP proxy for simple docker deployments to $container_name.domain.com. Just Add DNS record '* CNAME domain.com.' or '* IN A 123.123.123.123' that points to this container, and enjoy sites by address container_name.domain.com. Apps should listen port 80 inside container."
category: Utils
version: 1